version: '3.7'
services:
  db:
    image: postgres:15.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

    stdin_open: true
    tty: true
    entrypoint: ./docker/app-entrypoint.sh
    env_file:
      - .env

volumes:
  postgres: # named volume
